#!/bin/bash
# echo "Warning! You haven't set Python environment yet. Go to espnet/tools and generate 'activate_python.sh' using setup_anaconda.sh or setup_python.sh" >&2
# THIS FILE IS GENERATED BY tools/setup_python.sh
export PYTHONUSERBASE="/workspace/espnet/tools/python_user_base"
export PATH="/workspace/espnet/tools/python_user_base/bin":${PATH}
export PATH=/root/.virtualenvs/torch16-espnet/bin:${PATH}
